= Demo for testing mTLS in Confluent Cloud

This demonstrates how to use mTLS in Confluent Cloud

DISCLAIMER: This project is for demonstration purposes only. Using the demo unmodified in production is highly discouraged. Use at your own risk.

## Precondition

You need the following to run this demo:

* A Confluent Cloud Organization with support for mTLS (please contact Confluent as long as this features is not yet generally available)
* A Confluent Cloud API Key with sufficient access permissions to set up a dedicated cluster and an identity provider including identity pools
* Optionally, this demo can generate a certificate authority (CA) and client certificates in PEM as well as JKS format. For the conversion from PEM to JKS, both `openssl` as well as `keytool` need to be installed and in the PATH.

## Getting started

Set/customize some variables by copying `terraform.tfvars.template` to `terraform.tfvars`.

Open a shell and change into the `terraform` subfolder. In order to use your Confluent Cloud service account, either put your `api.txt` into that folder, or set the following environment variables to your API key:

```shell
export CONFLUENT_CLOUD_API_KEY="PUT YOUR API KEY HERE"
export CONFLUENT_CLOUD_API_SECRET="PUT YOUR API SECRET HERE"
```

If you start from scratch, initialize terraform once:

```shell
terraform init
```

Set 

Check the plan generated by terraform:

```shell
terraform plan
```

If you agree with the plan, deploy the resources (that will take some time):

```shell
terraform apply
```

== Testing the setup

Optionally, you can check the generated certificates against the certificate authority. In the `terraform` subfolder, run:

```shell
openssl verify -CAfile generated/certificates/ca_crt.pem generated/certificates/client_clientReadWrite_crt.pem
openssl verify -CAfile generated/certificates/ca_crt.pem generated/certificates/client_clientRead_crt.pem
```

In both cases, the result should be `OK`.

== Automatic Configuration

Terraform will have set up everything for your ideally. This includes a certificate authority, and two identity pools, one with read and one with write access to the topic `test` in the created dedicated cluster.

== Manual Configuration

=== Identity Pools

For now, you need to use the REST API to set up your certificate authority. Please refer to https://api.confluent.cloud/ for details.
Additionaly, you can set up identity pools. For this demo, we use two pools, one with read access and another one with write access to the topic `test` in the created dedicated cluster. You can use `CN` is certificate identifier and the following two filters:

```
SAN.contains("crn://DeveloperWriteTopicTest")
```

```
SAN.contains("crn://DeveloperReadTopicTest")
```

== Testing the setup

If you have created the certificiate authority and the client certificates, you can test your test setup immediately.
Please open a shell and enter the directory `terraform/generated`.

Have a look at the config files pre-configured for you. Three of them use API keys, two use mtls. Each config file contains an example on top.

You can for example start producing to the new cluster like this:

```shell
kafka-console-producer --producer.config client-clientReadWrite-mtls.conf --bootstrap-server <your-bootstrap-server:9092> --topic test
```

Note, as this feature is not yet released, you might face issues. As a paying customer, please contact Confluent if anything does not work.

== Wrapping things up

You can destroy all created resources including the cluster in Confluent Cloud by running the following command:

```shell
terraform destroy
```
